### ISSUE TITLE
Add ProBuilder dependency

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [BennyKok/HotspotUV#2]
I think ProBuilder should be a dependency in `package.json`.
```
"dependencies": {
	"com.unity.probuilder": "4.2.3"
}
```
I have used this for [my package](https://github.com/FreshlyBrewedCode/unity-mesh-tilesets/blob/master/Assets/Mesh%20Tilesets/package.json) as well and it works without problems.

**Comment by BennyKok** [comment]
Ok yea, right, thanks, will add it!!

**Comment by BennyKok** [comment]
Btw saw your package on Reddit some time ago, also inspired me to start this one!

**Comment by FreshlyBrewedCode** [comment]
I've been working on a similar tool lately. I'm not as far as you are because I focused on a generic approach and I spent too much time on my rect editor :D I will take a better look at your code and decide if I it is easier to PR my code into your repo or integrate your code into my project. Anyway, great job and glad to see this feature coming to Unity!

**Comment by BennyKok** [comment]
Oh yea, feel free man, for the rect editor, most zoom, pan stuff is from http://martinecker.com/martincodes/unity-editor-window-zooming/ , other than that is just grid-snapping and drawing extra GUI with Handles etc. took me sometimes to get the coords works right tho. I did think about having support for other modeling assets like umodeler, havnt really looked into their apis
